# Generated by Django 4.1.1 on 2022-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Input_str1', models.CharField(blank=True, max_length=300, null=True)),
                ('Input_str2', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
