# Generated by Django 4.1.1 on 2022-09-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utm_source', models.CharField(blank=True, max_length=250, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=250, null=True)),
                ('requestId', models.CharField(blank=True, max_length=250, null=True)),
                ('visitorId', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
